export const chapterTitles: Record<string, string> = {
    "chapter-100":  "Secrecy, Access, National Security, and Foreign Filing",
    "chapter-200":  "Types and Status of Application; Benefit and Priority Claims",
    "chapter-300":  "Ownership and Assignment",
    "chapter-400":  "Representative of Applicant or Owner",
    "chapter-500":  "Receipt and Handling of Mail and Papers",
    "chapter-600":  "Parts, Form, and Content of Application",
    "chapter-700":  "Examination of Applications",
    "chapter-800":  "Restriction in Applications Filed Under 35 U.S.C. 111; Double Patenting",
    "chapter-900":  "Prior Art, Classification, and Search",
    "chapter-1000": "Matters Decided by Various U.S. Patent and Trademark Office Officials",
    "chapter-1100": "Statutory Invention Registration (SIR); Pre-Grant Publication and Preissuance Submissions",
    "chapter-1200": "Appeal",
    "chapter-1300": "Allowance and Issue",
    "chapter-1400": "Correction of Patents",
    "chapter-1500": "Design Patents",
    "chapter-1600": "Plant Patents",
    "chapter-1700": "Miscellaneous",
    "chapter-1800": "Patent Cooperation Treaty",
    "chapter-1900": "Protest",
    "chapter-2000": "Duty of Disclosure",
    "chapter-2100": "Patentability",
    "chapter-2200": "Citation of Prior Art and Ex Parte Reexamination of Patents",
    "chapter-2300": "Interference Proceedings",
    "chapter-2400": "Biotechnology",
    "chapter-2500": "Maintenance Fees",
    "chapter-2600": "Optional Inter Partes Reexamination",
    "chapter-2700": "Patent Terms and Extensions",
    "chapter-2800": "Supplemental Examination",
    "chapter-2900": "International Design Applications",
}